// packages/@burger-editor/client/src/components/preview.tsx
import type { BurgerEditorEngine } from '@burger-editor/core';

import { useEffect, useState } from 'react';

import { getExt } from '../get-ext.js';
import { useComponentEvent } from '../use-engine.js';

import styles from './preview.module.css';

/**
 * File preview pane. The previewed path comes from the parent (lifted
 * from the old `file-select` observer event); upload progress stays on
 * the engine-level component observer.
 * @param root0
 * @param root0.engine
 * @param root0.path
 */
export function Preview({
	engine,
	path,
}: {
	readonly engine: BurgerEditorEngine;
	readonly path: string;
}) {
	const [dimension, setDimension] = useState<{
		readonly width: number;
		readonly height: number;
	} | null>(null);
	const [progress, setProgress] = useState({ uploaded: 0, total: 100 });

	const file = path ? getExt(path) : null;
	const isUploadingMode = path.startsWith('blob:');

	useComponentEvent(engine, 'file-upload-progress', (p) => {
		if (p.blob === path) {
			setProgress({ uploaded: p.uploaded, total: p.total });
		}
	});

	useEffect(() => {
		setDimension(null);

		const file = path ? getExt(path) : null;

		if (file?.isImage) {
			const image = new Image();
			image.src = path;
			image.addEventListener(
				'load',
				() => {
					setDimension({ width: image.naturalWidth, height: image.naturalHeight });
				},
				{ once: true },
			);
		} else if (file?.isVideo) {
			const video = document.createElement('video');
			video.src = path;
			video.addEventListener(
				'loadedmetadata',
				() => {
					setDimension({ width: video.videoWidth, height: video.videoHeight });
				},
				{ once: true },
			);
		}
	}, [path]);

	return (
		<div>
			<div
				className={`${styles['img']} ${isUploadingMode ? styles['uploading'] : ''}`.trim()}>
				{file?.isImage ? (
					<img src={path} alt="画像プレビュー" />
				) : file?.isVideo ? (
					<video controls playsInline>
						<source src={path} type={`video/${file.ext}`} />
						<track kind="captions" src="" />
					</video>
				) : file?.isAudio ? (
					<audio controls>
						<source src={path} type={`audio/${file.ext}`} />
						<track kind="metadata" src="" />
					</audio>
				) : file?.isDoc || file?.isPpt || file?.isXls || file?.isPdf ? (
					<object
						data={path}
						type={`application/${file.ext}`}
						title={`${file.ext}ファイルのプレビュー`}>
						<p>プレビューできません</p>
					</object>
				) : (
					<p>プレビューできません</p>
				)}
				{isUploadingMode ? (
					<div
						className={styles['progress']}
						style={{ translate: `${(progress.uploaded / progress.total) * 100}%` }}></div>
				) : null}
			</div>
			<ul className={styles['meta']}>
				{isUploadingMode ? (
					<li className={styles['upload']}>
						<span>アップロード...</span>
						<span className={styles['progress']}>
							{Math.round((progress.uploaded / progress.total) * 100)}% (
							{progress.uploaded}/{progress.total})
						</span>
					</li>
				) : (
					<li className={styles['path']}>
						<a href={path} target="_blank">
							{path}
						</a>
					</li>
				)}
				{dimension ? (
					<li className={styles['dimension']}>
						{dimension.width}x{dimension.height}
					</li>
				) : null}
			</ul>
		</div>
	);
}

// packages/@burger-editor/client/src/preview.svelte
<script lang="ts">
	import type { BurgerEditorEngine } from '@burger-editor/core';

	import { getExt } from './get-ext.js';
	export let engine: BurgerEditorEngine;

	let selectedPath = '';
	let width = Number.NaN;
	let height = Number.NaN;
	let file: ReturnType<typeof getExt> | null = null;

	let uploaded = 0;
	let total = 100;

	$: isUploadingMode = selectedPath.startsWith('blob:');

	engine.componentObserver.on('file-select', ({ path }) => {
		selectedPath = path;
		file = getExt(path);
	});

	engine.componentObserver.on('file-upload-progress', (progress) => {
		if (progress.blob === selectedPath) {
			uploaded = progress.uploaded;
			total = progress.total;
		}
	});

	$: {
		width = Number.NaN;
		height = Number.NaN;

		if (file?.isImage) {
			const image = new Image();
			image.src = selectedPath;
			image.addEventListener(
				'load',
				() => {
					width = image.naturalWidth;
					height = image.naturalHeight;
				},
				{ once: true },
			);
		} else if (file?.isVideo) {
			const video = document.createElement('video');
			video.src = selectedPath;
			video.addEventListener(
				'loadedmetadata',
				() => {
					width = video.videoWidth;
					height = video.videoHeight;
				},
				{ once: true },
			);
		}
	}
</script>

<div>
	<div class="img" class:uploading={isUploadingMode}>
		{#if file?.isImage}
			<img src={selectedPath} alt="画像プレビュー" />
		{:else if file?.isVideo}
			<video controls playsinline>
				<source src={selectedPath} type={`video/${file.ext}`} />
				<track kind="captions" src="" />
			</video>
		{:else if file?.isAudio}
			<audio controls>
				<source src={selectedPath} type={`audio/${file.ext}`} />
				<track kind="metadata" src="" />
			</audio>
		{:else if file?.isDoc || file?.isPpt || file?.isXls || file?.isPdf}
			<object
				data={selectedPath}
				type={`application/${file.ext}`}
				title={`${file.ext}ファイルのプレビュー`}>
				<p>プレビューできません</p>
			</object>
		{:else}
			<p>プレビューできません</p>
		{/if}
		{#if isUploadingMode}
			<div class="progress" style:translate={`${(uploaded / total) * 100}%`}></div>
		{/if}
	</div>
	<ul>
		{#if isUploadingMode}
			<li class="upload">
				<span>アップロード...</span>
				<span class="progress"
					>{Math.round((uploaded / total) * 100)}% ({uploaded}/{total})</span>
			</li>
		{:else}
			<li class="path"><a href={selectedPath} target="_blank">{selectedPath}</a></li>
		{/if}
		{#if !Number.isNaN(width) && !Number.isNaN(height)}
			<li class="dimension">{width}x{height}</li>
		{/if}
	</ul>
</div>

<style>
	.img {
		position: relative;
		overflow: hidden;

		img,
		video,
		audio,
		object,
		p {
			position: relative;
			z-index: 0;
			display: block;
			inline-size: 100%;
			aspect-ratio: 16 / 9;
			margin: 0;
			object-fit: contain;
		}

		p {
			display: flex;
			align-items: center;
			justify-content: center;
			background: rgb(0 0 0 / 10%);
		}

		&.uploading img {
			object-fit: cover;
		}

		.progress {
			position: absolute;
			inset-block-start: 0;
			z-index: 10;
			inline-size: 100%;
			block-size: 100%;
			background: rgb(0 0 0 / 50%);
		}
	}

	ul {
		display: flex;
		flex-wrap: wrap;
		gap: 0.3em;
		justify-content: center;
		padding: 0;
		padding-block-end: 1em;
		margin: 0;
		margin-block-start: 0.5em;
		font-family: monospace;
		font-size: calc(12 / 16 * 1em);
		opacity: 0.7;
	}

	li {
		display: block;
		padding: 0;
		margin: 0;
		list-style: none;
	}

	.path {
		word-break: break-all;

		a {
			color: inherit;
		}
	}

	.upload .progress {
		font-style: italic;
	}

	.dimension {
		&::before {
			content: '(';
		}

		&::after {
			content: ')';
		}
	}
</style>
