// packages/@burger-editor/client/src/components/tabs.tsx
import { useEffect, useId, useRef } from 'react';

import { useCommand } from '../use-command.js';

import styles from './tabs.module.css';

/**
 * Controlled tab list. Selection is lifted to the parent via
 * `current`/`onChange`; tab buttons declare a local command instead of a
 * click handler. Arrow keys move the selection.
 * @param root0
 * @param root0.current
 * @param root0.onChange
 * @param root0.contentId
 * @param root0.length
 * @param root0.createLabel
 * @example
 * ```tsx
 * <Tabs current={currentIndex} onChange={setCurrentIndex} contentId="tab-content" />
 * <div id="tab-content" role="tabpanel">
 * 	{currentIndex === 0 ? <PcForm /> : <SpForm />}
 * </div>
 * ```
 */
export function Tabs({
	current,
	onChange,
	contentId,
	length = 2,
	createLabel = (index) => `画像${index + 1}`,
}: {
	readonly current: number;
	readonly onChange: (index: number) => void;
	readonly contentId: string;
	readonly length?: number;
	readonly createLabel?: (index: number) => string;
}) {
	const listId = useId();
	const refs = useRef<(HTMLButtonElement | null)[]>([]);

	const update = (index: number) => {
		refs.current[index]?.focus();
		onChange(index);
	};

	const rootRef = useCommand<HTMLDivElement>({
		'--select-tab': (e) => {
			const value = (e.source as HTMLButtonElement | null)?.value;
			update(Number(value));
		},
	});

	useEffect(() => {
		const tabPanel = document.getElementById(contentId);
		if (!tabPanel) {
			throw new Error('Tab panel not found');
		}
		tabPanel.setAttribute('aria-label', createLabel(current));
	}, [contentId, current, createLabel]);

	const onKeyDown = (event: React.KeyboardEvent) => {
		if (event.key === 'ArrowLeft') {
			update(Math.max(0, current - 1));
		} else if (event.key === 'ArrowRight') {
			update(Math.min(length - 1, current + 1));
		}
	};

	return (
		<div role="tablist" ref={rootRef} id={listId} className={styles['tablist']}>
			{Array.from({ length }, (_, index) => (
				<button
					key={index}
					ref={(el) => {
						refs.current[index] = el;
					}}
					type="button"
					role="tab"
					aria-controls={contentId}
					aria-selected={current === index}
					tabIndex={current === index ? 0 : -1}
					command="--select-tab"
					commandfor={listId}
					value={index}
					onKeyDown={onKeyDown}>
					{createLabel(index)}
				</button>
			))}
		</div>
	);
}

// packages/@burger-editor/client/src/tabs.svelte
<script lang="ts">
	import type { BurgerEditorEngine } from '@burger-editor/core';

	import { onMount } from 'svelte';

	export let engine: BurgerEditorEngine;
	export let contentId: string;

	const refs: HTMLButtonElement[] = [];
	let tabPanel: HTMLElement | null = null;

	const length = 2;
	let currentIndex = 0;

	engine.componentObserver.on('select-tab-in-item-editor', ({ index }) => {
		currentIndex = index;
		refs[currentIndex]?.focus();
	});

	const onKeyDown = (event: KeyboardEvent) => {
		if (event.key === 'ArrowLeft') {
			update(Math.max(0, currentIndex - 1));
		} else if (event.key === 'ArrowRight') {
			update(Math.min(length - 1, currentIndex + 1));
		} else {
			return;
		}
	};

	const onClick = (index: number) => {
		update(index);
	};

	/**
	 *
	 * @param index
	 */
	function createLabel(index: number) {
		return `画像${index + 1}`;
	}

	/**
	 *
	 * @param index
	 */
	function update(index: number) {
		currentIndex = index;

		refs[currentIndex]?.focus();

		engine.componentObserver.notify('select-tab-in-item-editor', {
			index: currentIndex,
		});

		tabPanel?.setAttribute('aria-label', createLabel(currentIndex));
	}

	onMount(() => {
		tabPanel = document.getElementById(contentId);
		if (!tabPanel) {
			throw new Error('Tab panel not found');
		}
	});
</script>

<div role="tablist">
	{#each Array.from({ length }, (_, index) => index) as index (index)}
		<button
			type="button"
			role="tab"
			aria-controls={contentId}
			aria-selected={currentIndex === index}
			tabindex={currentIndex === index ? 0 : -1}
			onclick={() => onClick(index)}
			onkeydown={onKeyDown}
			bind:this={refs[index]}>
			{createLabel(index)}
		</button>
	{/each}
</div>

<style>
	:root {
		--border-radius: 0.5em;
	}

	[role='tablist'] {
		display: flex;
		gap: 0.5em;
		align-items: center;
		padding-inline: var(--border-radius);
	}

	[role='tab'] {
		position: relative;
		border: 1px solid var(--bge-border-color);
		border-end-start-radius: 0;
		border-end-end-radius: 0;

		&[aria-selected='true'] {
			border-block-end: none;

			&::after {
				position: absolute;
				inset-block-start: 100%;
				inset-inline-start: 50%;
				display: block;
				inline-size: 1em;
				block-size: 0.5em;
				content: '';
				background-color: var(--bge-ui-primary-color);
				clip-path: polygon(0 0, 50% 100%, 100% 0);
				translate: -50% 0;
			}
		}
	}
</style>
