// packages/@burger-editor/client/src/table-editor.svelte
<script lang="ts">
	import type { BurgerEditorEngine } from '@burger-editor/core';

	import IconArrowsTransferDown from '@tabler/icons-svelte/icons/arrows-transfer-down';
	import IconRowInsertBottom from '@tabler/icons-svelte/icons/row-insert-bottom';
	import IconTrash from '@tabler/icons-svelte/icons/trash';

	const { engine }: { engine: BurgerEditorEngine } = $props();

	type Data = {
		th: string[];
		td: string[];
	};
	type Table = [th: string, td: string][];

	let table: Table = $state([]);

	engine.componentObserver.on('open-editor', ({ data }) => {
		const { th, td } = data as Data;
		table = th.map((th, i) => [th, td[i] ?? '']);
		updateDataEl();
	});

	/**
	 *
	 * @param index
	 */
	function add(index: number) {
		table = table.toSpliced(index + 1, 0, ['', '']);
		updateDataEl();
	}

	/**
	 *
	 * @param index
	 */
	function remove(index: number) {
		table = table.toSpliced(index, 1);
		updateDataEl();
	}

	/**
	 *
	 * @param from
	 * @param to
	 */
	function move(from: number, to: number) {
		const fromRow = table[from]!;
		const toRow = table[to]!;
		table = table.toSpliced(from, 1, toRow);
		table = table.toSpliced(to, 1, fromRow);
		updateDataEl();
	}

	/**
	 * Updates the data element with new values.
	 * This function is responsible for modifying the data element
	 * based on the provided logic or parameters.
	 */
	function updateDataEl() {
		const dataEl = engine.itemEditorDialog.find<HTMLInputElement>('[name=bge]');
		if (!dataEl) {
			throw new Error('dataEl not found');
		}
		const data: Data = {
			th: table.map(([th]) => th),
			td: table.map(([, td]) => td),
		};
		dataEl.value = JSON.stringify(data);
	}
</script>

<div class="table">
	{#each table as row, i (i)}
		<div class="row">
			<div class="th">
				<textarea
					aria-label={`${i}行目の見出しセル`}
					name={`bge-th-${i}`}
					bind:value={row[0]}
					oninput={updateDataEl}></textarea>
			</div>
			<div class="td">
				<textarea
					aria-label={`${i}行目の内容セル`}
					name={`bge-td-${i}`}
					bind:value={row[1]}
					oninput={updateDataEl}></textarea>
			</div>
			<div class="btn">
				<ul>
					<li>
						<button type="button" title="下に追加" onclick={() => add(i)}>
							<IconRowInsertBottom />
						</button>
					</li>
					<li>
						<button
							type="button"
							title="削除"
							disabled={table.length === 1}
							onclick={() => remove(i)}>
							<IconTrash />
						</button>
					</li>
					<li>
						<button
							type="button"
							title="下に移動"
							disabled={i === table.length - 1}
							onclick={() => move(i, i + 1)}>
							<IconArrowsTransferDown class="icon" />
						</button>
					</li>
				</ul>
			</div>
		</div>
	{/each}
</div>

<style>
	.table {
		display: grid;
		grid-template-columns: minmax(1em, 1fr) minmax(1em, 1fr) auto;
		gap: 0.5em 1em;
	}

	.row {
		display: grid;
		grid-template-columns: subgrid;
		grid-column: span 3;
		align-items: center;
	}

	textarea {
		inline-size: 100%;
		resize: vertical;
	}

	.btn ul {
		display: flex;
		gap: 0.3em;
		padding: 0;
		margin: 0;
	}

	.btn li {
		padding: 0;
		margin: 0;
		list-style: none;
	}
</style>

// packages/@burger-editor/client/src/components/table-editor.tsx
import {
	IconArrowsTransferDown,
	IconRowInsertBottom,
	IconTrash,
} from '@tabler/icons-react';
import { useId } from 'react';

import { useCommand } from '../use-command.js';

import styles from './table-editor.module.css';

export interface TableEditorData {
	readonly th: readonly string[];
	readonly td: readonly string[];
}

/**
 * Table row editor as a fully controlled component. The table item's
 * editor owns the state; row operations are declared as local commands.
 * @param root0
 * @param root0.value
 * @param root0.onChange
 */
export function TableEditor({
	value,
	onChange,
}: {
	readonly value: TableEditorData;
	readonly onChange: (value: TableEditorData) => void;
}) {
	const rootId = useId();

	const rows: readonly [th: string, td: string][] = value.th.map((th, i) => [
		th,
		value.td[i] ?? '',
	]);

	const commit = (next: readonly [string, string][]) => {
		onChange({
			th: next.map(([th]) => th),
			td: next.map(([, td]) => td),
		});
	};

	const rootRef = useCommand<HTMLDivElement>({
		'--add-row': (e) => {
			const index = Number((e.source as HTMLButtonElement | null)?.value);
			commit(rows.toSpliced(index + 1, 0, ['', '']));
		},
		'--remove-row': (e) => {
			const index = Number((e.source as HTMLButtonElement | null)?.value);
			commit(rows.toSpliced(index, 1));
		},
		'--move-row-down': (e) => {
			const from = Number((e.source as HTMLButtonElement | null)?.value);
			const to = from + 1;
			const fromRow = rows[from];
			const toRow = rows[to];
			if (!fromRow || !toRow) {
				return;
			}
			commit(rows.toSpliced(from, 1, toRow).toSpliced(to, 1, fromRow));
		},
	});

	return (
		<div className={styles['table']} ref={rootRef} id={rootId}>
			{rows.map(([th, td], i) => (
				<div className={styles['row']} key={i}>
					<div className={styles['th']}>
						<textarea
							aria-label={`${i}行目の見出しセル`}
							name={`bge-th-${i}`}
							value={th}
							onChange={(e) => {
								commit(rows.with(i, [e.currentTarget.value, td]));
							}}></textarea>
					</div>
					<div className={styles['td']}>
						<textarea
							aria-label={`${i}行目の内容セル`}
							name={`bge-td-${i}`}
							value={td}
							onChange={(e) => {
								commit(rows.with(i, [th, e.currentTarget.value]));
							}}></textarea>
					</div>
					<div className={styles['btn']}>
						<ul>
							<li>
								<button
									type="button"
									title="下に追加"
									command="--add-row"
									commandfor={rootId}
									value={i}>
									<IconRowInsertBottom />
								</button>
							</li>
							<li>
								<button
									type="button"
									title="削除"
									disabled={rows.length === 1}
									command="--remove-row"
									commandfor={rootId}
									value={i}>
									<IconTrash />
								</button>
							</li>
							<li>
								<button
									type="button"
									title="下に移動"
									disabled={i === rows.length - 1}
									command="--move-row-down"
									commandfor={rootId}
									value={i}>
									<IconArrowsTransferDown className="icon" />
								</button>
							</li>
						</ul>
					</div>
				</div>
			))}
		</div>
	);
}
