// packages/@burger-editor/client/src/thumbnail.svelte
<script lang="ts">
	import IconFile from '@tabler/icons-svelte/icons/file';
	import IconFileTypeDoc from '@tabler/icons-svelte/icons/file-type-doc';
	import IconFileTypePdf from '@tabler/icons-svelte/icons/file-type-pdf';
	import IconFileTypePpt from '@tabler/icons-svelte/icons/file-type-ppt';
	import IconFileTypeXls from '@tabler/icons-svelte/icons/file-type-xls';
	import IconHandphones from '@tabler/icons-svelte/icons/headphones';
	import IconVideo from '@tabler/icons-svelte/icons/video';

	import { getExt } from './get-ext.js';

	export let src: string;
	let isLoaded = false;

	const file = getExt(src);
</script>

<span data-bge-editor-ui-component="thumbnail" data-loaded={isLoaded}>
	{#if file.isImage}
		<img {src} alt="画像のプレビュー" loading="lazy" onload={() => (isLoaded = true)} />
	{:else if file.isVideo}
		<video controls={false} playsinline>
			<source {src} type={`video/${file.ext}`} />
			<track kind="captions" src="" />
			<IconVideo />
		</video>
	{:else if file.isAudio}
		<IconHandphones />
	{:else if file.isDoc}
		<IconFileTypeDoc />
	{:else if file.isPpt}
		<IconFileTypePpt />
	{:else if file.isXls}
		<IconFileTypeXls />
	{:else if file.isPdf}
		<IconFileTypePdf />
	{:else}
		<IconFile />
	{/if}
</span>

<style>
	span {
		display: block;
		inline-size: 100%;
		block-size: 100%;
	}

	img,
	video {
		display: block;
		inline-size: 100%;
		block-size: 100%;
		object-fit: cover;
		transition: opacity 300ms linear;
	}

	[data-loaded='false'] img {
		opacity: 0;
	}

	[data-loaded='true'] img {
		opacity: 1;
	}
</style>

// packages/@burger-editor/client/src/components/thumbnail.tsx
import {
	IconFile,
	IconFileTypeDoc,
	IconFileTypePdf,
	IconFileTypePpt,
	IconFileTypeXls,
	IconHeadphones,
	IconVideo,
} from '@tabler/icons-react';
import { useState } from 'react';

import { getExt } from '../get-ext.js';

import styles from './thumbnail.module.css';

/**
 * File thumbnail. Renders an image/video preview or a file-type icon.
 * @param root0
 * @param root0.src
 */
export function Thumbnail({ src }: { readonly src: string }) {
	const [isLoaded, setIsLoaded] = useState(false);

	const file = getExt(src);

	return (
		<span
			className={styles['thumbnail']}
			data-bge-editor-ui-component="thumbnail"
			data-loaded={isLoaded}>
			{file.isImage ? (
				<img
					src={src}
					alt="画像のプレビュー"
					loading="lazy"
					onLoad={() => setIsLoaded(true)}
				/>
			) : file.isVideo ? (
				<video controls={false} playsInline>
					<source src={src} type={`video/${file.ext}`} />
					<track kind="captions" src="" />
					<IconVideo />
				</video>
			) : file.isAudio ? (
				<IconHeadphones />
			) : file.isDoc ? (
				<IconFileTypeDoc />
			) : file.isPpt ? (
				<IconFileTypePpt />
			) : file.isXls ? (
				<IconFileTypeXls />
			) : file.isPdf ? (
				<IconFileTypePdf />
			) : (
				<IconFile />
			)}
		</span>
	);
}
